/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_violet_MathKit */

#ifndef _Included_com_violet_MathKit
#define _Included_com_violet_MathKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_violet_MathKit
 * Method:    square
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_violet_MathKit_square
        (JNIEnv *, jclass, jint);

/*
 * Class:     com_violet_MathKit
 * Method:    appendStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_violet_MathKit_appendStr
        (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
