/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <com_violet_MathKit.h>
#include<string.h>


JNIEXPORT jint JNICALL Java_com_violet_MathKit_square(JNIEnv *env, jclass cls, jint num){
  return num*num;
}

JNIEXPORT jstring JNICALL Java_com_violet_MathKit_appendStr  (JNIEnv *env, jclass cls, jstring str){
  // 字符串转char
  const char *strUTF = env->GetStringUTFChars(str, 0);
  char szBuffer[256];
  strcpy(szBuffer, strUTF);

  env->ReleaseStringUTFChars(str, strUTF);

  strcat(szBuffer,"当我登上月球我会说");

  return env->NewStringUTF(szBuffer);
}